### ISSUE TITLE
jQuery promise dependency -> ES6 promise

### ISSUE THREAD

**Issue by DGolverdingen** [progress/JSDO#101]
The dependency on jQuery promises is not very helpful for modern web application development. 
Currently I have to add jQuery in an Angular (4) project to be able to use JSDOSession.

Please move to ES6 promises or create an ES6 version because the ability to use Async / Await  or the native Promise handlers on methods like getSession() will improve the usability.

**Comment by edselg** [comment]
Hello @DGolverdingen ,

Thank you for your feedback.

It is possible to use the current a wrapper class to ES6 promises instead of jQuery.
Would you be interested on trying this approach?

The support for NPM, Promises and TypeScript is a new project and we are still working on it.

We should have additional updates in this repository and the develop repository as part of the work in the future version.

Thanks.

**Comment by edselg** [comment]
Support for ES6 Promises was added to the JSDO in the develop branch.
By default, the JSDO now uses ES6 Promises.

The progress.util.Deferred.useJQueryPromises property can be set to true for cases when the new JSDO library needs to be used with jQuery Promises.
