### ISSUE TITLE
Error using JSDO with SCL and Kendo Grid generated from the Business Entity designer

### ISSUE THREAD

**Issue by chunnybryan** [progress/JSDO#205]
When using the JSDO 5.5 with the SCL and the Kendo Grid generated from the BE designer you receive the following error:

Type Error: promise.done is not a function.

![image](https://user-images.githubusercontent.com/42641093/44521520-3dc9b000-a6cb-11e8-8dad-f321ba60a1c9.png)

This error does not occur with JSDO 4.2 or 4.4.

**Comment by chunnybryan** [comment]
`

`

**Comment by chunnybryan** [comment]
[JobRetentionBE.txt](https://github.com/progress/JSDO/files/2314116/JobRetentionBE.txt)

**Comment by edselg** [comment]
Hello @chunnybryan ,

_**> Type Error: promise.done is not a function.**_

JSDO 5.0 uses ES6 Promises by default.
Th error message that you are seeing happens because the ES6 Promise object does not have a done() function. It has a then(<success handler>, <error handler>) function instead.
Link: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

There are two ways to solve this error.

1)
If you prefer to use ES6 Promises, then you would need to update your code to use the functions.
Also, please notice that the new signature uses a single parameter from where you can access the old parameters as properties.
Example:
promise.done(function(jsdosession, result, info) {
would need to change to 
promise.then(function(object) {
/* query object.jsdosession, object.result, object.info */

2) 
If you prefer to use jQuery Promises with JSDO 5.0, then you can add tell the JSDO to use jQuery Promises instead of ES6.
Code:
`progress.util.Deferred.useJQueryPromises = true;`

Notes:
You can use the JSDO with ES6 Promises with Kendo UI for jQuery or AngularJS.
However, when working with Kendo UI for Angular you would use only ES6 Promises since jQuery is not used.

Please give one of these suggestions a try and let me know if you need additional information.

Thank you and regards.

**Comment by chunnybryan** [comment]
Thanks Edselg.

I have the tried the 2nd option and it works!

**Comment by edselg** [comment]
Great!
