### ISSUE TITLE
JSDO login failes with Safari on Apple MacOS and IOS

### ISSUE THREAD

**Issue by DGolverdingen** [progress/JSDO#206]
When logging in on published and build Angular test site with new JSDO, Safari is failing on getting the home.html file.

Deployed site URL: https://jsdotest.firebaseapp.com/
Git repo: https://github.com/DGolverdingen/angular6jsdo

The JSON is only showing "result": 1

![microsoftteams-image](https://user-images.githubusercontent.com/29942500/44713527-988c4e80-aab3-11e8-9c93-61f7ae317f05.png)

Network trace:

![microsoftteams-image 3](https://user-images.githubusercontent.com/29942500/44714293-3f251f00-aab5-11e8-9a5a-b8aadce4f970.png)

This might be more a Safari issue and not a JSDO specific version issue, but still, a solution should be found how to support multi-device and OS.

**Comment by edselg** [comment]
Hello @DGolverdingen 

I just tested and I was not able to reproduce the issue using Safari 11.1.1 (13605.2.8) and Safari 11.1.2 (13605.3.8).
The access to home.html is successful.

Do you still see the issue in your environment?

Please let me know.

Thank you and regards.

**Comment by DGolverdingen** [comment]
Yes, we have this problem on multiple devices. Chrome on IOS does work, Safari isn't.
Is the server located in your local network? Did you test it for example with an iPhone and mobile internet connection? We tested it on 4g, public wifi, intranet wifi.

**Comment by DGolverdingen** [comment]
Yes, on Ipad Air 1, iPhone 6, Macbook Pro on public network

**Comment by Malachute** [comment]
@edselg is it possible for you to take another look at this issue? I've updated Dgolverdingen's git to Angular 7 with JSDO 6 here: https://gitlab.com/Malachute/angular7-jsdo
And deployed it to: https://angular7jsdo-safari-test.firebaseapp.com/

Background turns green when loginResult returns 1, otherwise it stays red.

Below is a list of operating systems and browsers used + the result. All tests were done via Browserstack.com, using the newest devices and browsers versions.

|               OS               | Browser | Result |
|:------------------------------:|:-------:|:------:|
| Mac OS                         |  Chrome |  Works |
|                                |  Safari |   Fail |
|                                | Firefox |   Fail |
|                                | Opera   | Works  |
|                                | | |
| Windows 10                     | Edge    | Works  |
|                                | IE11    | Works  |
|                                | Chrome  | Works  |
|                                | Firefox | Fail   |
|                                | Opera   | Works  |
|                                | | |
| iOS                            | Safari  | Fail   |
| (iPad PRO 11inch  + iPhone Xr) | Chrome  | Fail   |
|                                | | |
| Android                        |      Chrome     |  Works |
| (Galaxy S8)                    | Samung Internet |   Fail |
|                                |     Firefox     |   Fail |

**Comment by edselg** [comment]
Hello @Malachute ,

Thank you for the additional information.

I was able to see the issue on iOS using Edge, Firefox and Opera.
However, I was not able to see the issue using Safari.

I will let you know what I find on my research.

|  OS  |  Browser  |  Result  |
| ------------- | ------------- | ------------- |
| Windows 10 | Edge | Works |
  | Firefox (64.0.2 and 65.0.1) | Works
  | Opera | Works
iOS 12.1.2 (iPhone) | Safari | Works
  | Firefox | Fails
  | Edge | Fails
  | Opera | Fails
iOS 12.1.3 (iPad) | Safari | Works
  | Edge | Fails
  | Firefox | Fails
  | Opera | Fails

**Comment by edselg** [comment]
Internal issue # ADAS-15443.

**Comment by zerovian** [comment]
This has been moved to internal Issue # OCTA-11853

**Comment by Malachute** [comment]
Hi @edselg & @zerovian 
Is there an update on this issue?
Thanks!

**Comment by edselg** [comment]
Hello @Malachute 

I did some additional testing of the issue using iOS 13 public beta 2.

I found the following:
iPadOS 13.0 (public beta 2) (iPad) | Safari | Works
  | Edge | Fails
  | Firefox | Works
  | Opera Touch | Fails
  | Google Chrome | Fails

I find interesting that it now works with Firefox.
Safari was already working in iOS 12.1.2.

This seems to indicate that the issue is not on the JSDO side but on some of the inner working of the web browser.

What iOS version and web browsers are your targeting with your application?
Do you also get Safari to work in your environment?

I hope this helps.

**Comment by audaciousanil** [comment]
Hello @Malachute 

I can reproduce the problem in Safari browser in iOS (12.3.1) and in MacOS (Mojave). i.e., When ‘Prevent Cross-Site Tracking’ option is checked/enabled it fails to load this page (https://angular7jsdo-safari-test.firebaseapp.com/) in Safari browser in both iOS and MacOS. i.e., it returns ‘result code: 1’ followed by 401 error (Not Authenticated).
When ‘Prevent Cross-Site Tracking’ option is not selected, and accessing this page (https://angular7jsdo-safari-test.firebaseapp.com/) in a new private window/tab in Safari browser in iOS or MacOS it works just fine.

Can you please check for the settings of ‘Prevent Cross-Site Tracking’ option (Settings -> Safari -> Privacy & Security) in your environment (iOS and MacOS)? Also, can you try to uncheck this option and load the app (https://angular7jsdo-safari-test.firebaseapp.com/)) in a new private Safari browser/window and see if this setting resolved the problem.

**Technical details**: We are using JSESSIONID cookies as part of the JSDO’s FORM authentication in communication with PASOE server. When the cookies are blocked in browsers then we run into these authentication issues. i.e., if the third-party cookies are blocked then the **result code** **_1_** is issued. If all 3rd party requests are blocked, then the **result code** **_null_** is issued. 

**Note**: Following article says Apple will block cookies and website data when we enable ‘Prevent cross site tracking’ option in Safari in iOS or MacOS
	https://support.apple.com/guide/safari/prevent-cross-site-tracking-sfri40732/mac

**Comment by audaciousanil** [comment]
**Additional Testing Performed**: In order to isolate the problem, I also verified ANONYMOUS and BASIC authentication in all three browsers (Safari, Chrome and Firefox) in iOS device and both authentication types are working fine.
